[build]
builder = "nixpacks"
buildCommand = "npm install && cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 