[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && cd ../frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 